- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
#    - name: "Destroy Azure Deploy  Resource group {{ resource_group_name }}"
#      azure_rm_deployment:
 #       state: absent
 #       subscription_id: "{{ subscriptionID }}"
 #       resource_group_name: "{{ resource_group_name }}"
#        location: "{{ region }}"
################################################
####  Create basic infra components
################################################
    - name: "Create Azure Deploy {{ resource_group_name }}"
      azure_rm_deployment:
        state: present
        ad_user: "{{ ad_username }}"
        password: "{{ ad_password }}"
        subscription_id: "{{ subscriptionID }}"
        resource_group_name: "{{ resource_group_name }}"
        template_link: 'https://raw.githubusercontent.com/ivanthelad/ansible-azure/master/infra-avail.json'
      #  template_link: 'file://Users/imckinle/Projects/openshift/azure-ansible/ansible-azure/infra-avail.json'
        parameters:
          dnsNameAPI:
            value: "master-{{ resource_group_name }}"
        location: "{{ region }}"
      register: infrastruct

    - debug: msg="the value of infrastruct  {{ infrastruct }}"
    - debug: msg="the value of infrastruct {{ infrastruct }}"
    - set_fact:
        apiip: "{{ infrastruct.deployment.outputs.apiip.value }}"
        apidns: "{{ infrastruct.deployment.outputs.apidns.value }}"
        routerip: "{{ infrastruct.deployment.outputs.routerip.value }}"
        jumphostip: "{{ infrastruct.deployment.outputs.jumphostip.value }}"
    - debug: msg="{{ apiip }}"
    - debug: msg="{{ apidns }}"
    - debug: msg="{{ routerip }}"
    - debug: msg="{{ jumphostip }}"


################################################
####  Create basic Master node, this exposes 8443 and 22 as a public ports on a public ip , in future this will be a jump host
###   we use this node to jump into the other nodes
################################################
################################################
#### Creating the masters nodes. these sit behind the jump host. no need to open public ports
####Todo, dyncamically add the list of infra nodes to group
################################################
- hosts: localhost
  strategy: free
  serial: 20
  connection: local
  vars:
      masterkey: "{{ lookup('file', '/tmp/id_rsa.tmp') }}"
  gather_facts: no
  tasks:
    - name: Create Masters Deploy
      async: 7200
      poll: 0
      with_dict: "{{ masters }}"
      delay: 30
      retries: 1
      azure_rm_deployment:
        deployment_mode: incremental
        state: present
        ad_user: "{{ ad_username }}"
        password: "{{ ad_password }}"
        subscription_id: "{{ subscriptionID }}"
        resource_group_name: "{{ resource_group_name }}"
        location: "{{ region }}"
        deployment_name: "{{ item.value.name }}"
        parameters:
          subnetName:
            value: masterSubnet
          virtualNetworkName:
            value: openshiftVnet
          adminUsername:
            value: "{{ adminUsername }}"
          vmSize:
            value: "{{ node_vmSize }}"
          adminPassword:
            value: "{{ adminPassword }}"
          image:
            value: rhel
          masterKey:
            value: "{{ masterkey }}"
          tags:
            value: "{{ item.value.tags }}"
          vmName:
            value: "{{ item.value.name }}"
          sshKeyData:
            value: "{{ sshkey }}"
          availabilitySetName:
            value: "masterAvailSet"
          loadBalancer:
            value: "apiPool"

## ip address has to be created before hand  for some reason i cannot fathom at the mo
          publicip:
            value: "apipublicip"
          internalLoadbalancerip:
            value: "10.0.3.11"

        template_link: 'https://raw.githubusercontent.com/ivanthelad/ansible-azure/master/masters-avail.json'
        #i#template_link: 'ansible-azure/nodes.json'
      register: azuremasternodes_sync


################################################
#### Creating the infrastrucute nodes.
####Todo, dyncamically add the list of infra nodes to group
################################################
    - name: Create infra Nodes Deploy
      with_dict: "{{ infranodes }}"
      async: 7200
      poll: 0
      azure_rm_deployment:
        deployment_mode: incremental
        state: present
        ad_user: "{{ ad_username }}"
        password: "{{ ad_password }}"
        subscription_id: "{{ subscriptionID }}"
        resource_group_name: "{{ resource_group_name }}"
        location: "{{ region }}"
        deployment_name: "{{ item.value.name }}"
        parameters:
          subnetName:
            value: infranodeSubnet
          virtualNetworkName:
            value: openshiftVnet
          adminUsername:
            value: "{{ adminUsername }}"
          vmSize:
            value: "{{ node_vmSize }}"
          adminPassword:
            value: "{{ adminPassword }}"
          image:
            value: rhel
          masterKey:
            value: "{{ masterkey }}"
          tags:
            value: "{{ item.value.tags }}"
          vmName:
            value: "{{ item.value.name }}"
          sshKeyData:
            value: "{{ sshkey }}"
          availabilitySetName:
            value: "infranode-AvailSet"
          loadBalancer:
            value: "router"

            ## ip address has to be created before hand  for some reason i cannot fathom at the mo
          publicip:
            value: "routerip"
        template_link: 'https://raw.githubusercontent.com/ivanthelad/ansible-azure/master/infranode-avail.json'
        #i#template_link: 'ansible-azure/nodes.json'
      register: azureinfranodes_async


################################################
#### Creating the application nodes.
####Todo, dyncamically add the list of infra nodes to group
################################################
    - name: Create Nodes Deploy
      async: 7200
      poll: 0
      with_dict: "{{ nodes }}"
      azure_rm_deployment:
        ad_user: "{{ ad_username }}"
        password: "{{ ad_password }}"
        subscription_id: "{{ subscriptionID }}"
        deployment_mode: incremental
        state: present
        subscription_id: "{{ subscriptionID }}"
        resource_group_name: "{{ resource_group_name }}"
        location: "{{ region }}"
        deployment_name: "{{ item.value.name }}"
        parameters:
          subnetName:
            value: nodeSubnet
          virtualNetworkName:
            value: openshiftVnet
          adminUsername:
            value: "{{ adminUsername }}"
          vmSize:
            value: "{{ node_vmSize }}"
          adminPassword:
            value: "{{ adminPassword }}"
          image:
            value: rhel
          masterKey:
            value: "{{ masterkey }}"
          tags:
            value: "{{ item.value.tags }}"
          vmName:
            value: "{{ item.value.name }}"
          sshKeyData:
            value: "{{ sshkey }}"
          availabilitySetName:
            value: "nodeAvailSet"

 ## simple nodes
        template_link: 'https://raw.githubusercontent.com/ivanthelad/ansible-azure/master/nodes-avail.json'
        #i#template_link: 'ansible-azure/nodes.json'
      register: azurenodes_async


## wait for infra nodes
    - name: Wait for infranode instance creation to complete
      async_status: jid={{ item.ansible_job_id }}
      register: azureinfranodes
      until: azureinfranodes.finished
      retries: 900
      with_items: "{{ azureinfranodes_async.results }}"

### wait for masters
    - name: Wait for master instance creation to complete
      async_status: jid={{ item.ansible_job_id }}
      register: azuremasternodes
      until: azuremasternodes.finished
      retries: 900
      with_items: "{{ azuremasternodes_sync.results }}"

## wait for infra nodes
    - name: Wait for infranode instance creation to complete
      async_status: jid={{ item.ansible_job_id }}
      register: azureinfranodes
      until: azureinfranodes.finished
      retries: 900
      with_items: "{{ azureinfranodes_async.results }}"

### wait for nodes
    - name: Wait for nodes instance creation to complete
      async_status: jid={{ item.ansible_job_id }}
      register: azurenodes
      until: azurenodes_async.finished
      retries: 900
      with_items: "{{ azurenodes_async.results }}"



    - debug: msg="the value of (INFRA)azureinfranodes {{ azureinfranodes }}"


    - debug: msg="the value of (MASTERS)azuremasternodes {{ azuremasternodes }}"
    - debug: msg="the value of (NODES)azurenodes {{ azurenodes }}"
    - debug: msg="the value of (INFRA)azureinfranodes {{ azureinfranodes }}"

















