---
- name: Copy the pc file
  copy: src="logging-service.yml" dest="."
  tags: logging

- name: Copy the PV file
  copy: src="es-pv.json" dest="."
  tags: logging

- name: Copy the PVC file
  copy: src="es-pvc.json" dest="."
  tags: logging


- debug: msg="creating project logging"
- name: Set the node-selector for the default namespace
  shell: "oadm new-project logging "
  ignore_errors: true

- name: 
  action: command oc secrets new logging-deployer nothing=/dev/null -n logging
  ignore_errors: yes
  tags: logging

- name:
  action: command oc create -f logging-service.yml -n logging
  tags: logging

- name:
  action: command  oc policy add-role-to-user edit --serviceaccount logging-deployer -n logging
  tags: logging

- name:
  action: command  oadm policy add-scc-to-user  privileged system:serviceaccount:logging:aggregated-logging-fluentd -n logging
  tags: logging

- name: 
  action: command oadm policy add-cluster-role-to-user cluster-reader system:serviceaccount:logging:aggregated-logging-fluentd -n logging 
  tags: logging

#- name: Creating ES PV
#  action: command oc create -f es-pv.json
#  tags: logging

- name:  deploy logging-deployer-template  
  action: command  oc new-app logging-deployer-template --param KIBANA_HOSTNAME={{ kibana_hostname }} \
             --param MASTER_URL={{ master_url }} \
             --param ES_CLUSTER_SIZE=1 \
             --param IMAGE_VERSION={{ image_version }} \
             --param PUBLIC_MASTER_URL={{ public_master_url }} -n logging
  tags: logging

- name: Waiting 100 seconds  until the logging-support-template template is available before executing next comand
  command: oc get template logging-support-template -n logging
  retries: 20
  delay: 10
  until: result|success
  register: result

#- name: ES Volume Claim
#  action: command oc create -f es-pvc.json -n logging
#  tags: logging

- name: oc new-app logging-support-template -n logging
  command: oc new-app logging-support-template -n logging
  tags: logging 

- name: get dc 
  command:  oc get dc -n logging
  tags: logging 
  retries: 5
  delay: 5
  until: result|success
  register: result

- shell: "echo sleeping for 100 seconds "
- shell: sleep 100
- name: grep
  shell: "oc get dc -n logging | awk '{print $1}' | grep logging-es "
  register: result
- debug: msg="{{ result.stdout  }}"
- shell: " oc get dc {{ result.stdout  }} -n logging "
  register: dc
- debug: msg=" changing deployment config  {{ dc  }}"
- shell: "oc get nodes  --no-headers  | wc -l"
  register: replicas
#i#- shell: "oc volume deploymentconfigs {{ result.stdout  }}  --add --overwrite --name=elasticsearch-storage --type=persistentVolumeClaim --claim-name=elastic-search-claim"
- shell: "oc scale dc/logging-fluentd --replicas={{ replicas.stdout  }} -n logging"
  name: "Scalling to fluentd  replicas"
  
