

- hosts: gatewayed-nodes
  user: "{{ adminUsername }}"
  sudo: true
  vars:
    publicjumpdns: "{{ hostvars['localhost']['publicjumpdns']}}"
    publicjumpip: "{{ hostvars['localhost']['publicjumpip']}}"
    routerpublicip: "{{ hostvars['localhost']['routerpublicip']}}"
    ansible_ssh_common_args: -o ProxyCommand="ssh -W %h:%p -q {{ adminUsername }}@{{ publicjumpip }}"
    docker_storage_device: "/dev/sdc"

  name: test play
  tasks:

      - shell: findmnt -no SOURCE
        register: sdccheck

      - debug: msg="The /dev/sdc is already in use. This is because microsoft has the /mnt/resource temp directory  which ordinarly should be using the device /dev/sdb but for some reason unbeknownst to me the MS gods have decided, 'no, screw this. today i wana use /dev/sdc, you figure something else out'. Anyway. what this means is now is gota have this hacky check to see if sdc is already in use, if it is i gota tell docker to use sdb which is where my flipping storage is. Get you crap together MS. this is probably longer that a debug statement should be.  "
        when: sdccheck.stdout.find('sdc') != -1

      - set_fact:
          docker_storage_device: "/dev/sdb"
        when: sdccheck.stdout.find('sdc') != -1

      - debug: msg="Ok new device set, docker_storage_device={{docker_storage_device}}"
